version: "3.9"
services:
  backend-oscars:
    build:
      context: ./backend-oscars
    image: backend-oscars:local
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
    restart: unless-stopped


