services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: unless-stopped
  backend-oscars:
    build:
      context: ./backend-oscars
    image: backend-oscars:local
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
#      - DB_URL=jdbc:postgresql://postgres:5432/********
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    restart: unless-stopped

  backend-films:
    build:
      context: ./backend-films
    image: backend-films:local
    ports:
      - "8081:8080"
      - "9991:9990"
      - "8444:8443"
    environment:
      JAVA_OPTS: ""
      MGMT_USER: admin
      MGMT_PASS: admin123!
      DB_URL: jdbc:postgresql://postgres:5432/filmsdb
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_MOVIES_API_URL: "http://backend-films:8081"
      NEXT_PUBLIC_OSCARS_API_URL: "http://backend-oscars:8080"

    depends_on:
      - backend-oscars
      - backend-films

  keycloak:
    image: keycloak/keycloak:26.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123!
    command: start-dev
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
  postgres_data:
