services:
  postgres-soa:
    image: postgres:16
    container_name: postgres-soa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: unless-stopped
  backend-oscars:
    build:
      context: ./backend-oscars
    image: backend-oscars:local
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=
      - DB_URL=jdbc:postgresql://postgres-soa:5432/oscarsdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres-soa
    restart: unless-stopped

  backend-films:
    build:
      context: ./backend-films
    image: backend-films:local
    ports:
      - "8080:8080"
      - "9991:9990"
      - "8444:8443"
    environment:
      JAVA_OPTS: ""
      MGMT_USER: admin
      MGMT_PASS: admin123!
      DB_URL: jdbc:postgresql://postgres-soa:5432/filmsdb
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres-soa
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_MOVIES_API_URL: "http://localhost:8080"
      NEXT_PUBLIC_OSCARS_API_URL: "http://localhost:8081"
      # Для Docker профиля - без basePath
      NEXT_PUBLIC_BASE_PATH: ""

    depends_on:
      - backend-oscars
      - backend-films

  keycloak:
    image: keycloak/keycloak:26.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123!
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-soa:5432/keycloakdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command: start-dev
    ports:
      - "8082:8080"
    depends_on:
      - postgres-soa
    restart: unless-stopped
    volumes:
      - ./keycloak-setup.sh:/opt/keycloak-setup.sh:ro

volumes:
  postgres_data:
