spring:
  application:
    name: backend-oscars
  main:
    log-startup-info: false
  logging:
    use-logback: false

server:
  port: 8132

movies:
  api:
    base-url: http://localhost:8081/api

# Disable Spring Boot's default logging configuration
logging:
  use-logback: false
