spring:
  application:
    name: backend-oscars
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cachecontrol:
          max-age: 3600
server:
  port: 37862
  servlet:
    context-path: /
movies:
  api:
    base-url: http://localhost:37861/api